### ISSUE TITLE
希望能提供字体大小自定义设定

### ISSUE THREAD

**Issue by Gokou-Ruri** [xzr467706992/PerfMon-Plus#1]
如图，这个尺寸实在是太大了，请开发者提供一个字号设定选项。
![b744966394135b9986e0e142b6a19243](https://user-images.githubusercontent.com/26711804/67229739-80714e80-f46e-11e9-9d39-c7464d82ceb4.jpg)

希望能够显示比perfmon（右）更小的字号。
![Screenshot_Nova_Launcher_20191022-015314](https://user-images.githubusercontent.com/26711804/67229885-ce865200-f46e-11e9-829d-38d5b0f292ee.png)

小声bb：其实“温度”、“内存”、“电流”用英文缩写显示的话会让界面更加统一。

**Comment by libxzr** [comment]
Done 
https://github.com/xzr467706992/PerfMon-Plus/commit/138e1f286cf394477d753ed76089b2692346815c
