### ISSUE TITLE
Create a separate activity for monitor window

### ISSUE THREAD

**Issue by obscenelyvague** [xzr467706992/PerfMon-Plus#3]
Currently everything happens inside MainActivity; which means no matter what everyone has to go through the first "preferences" window to get to the monitor window. However,  I'd like to open the monitor window itself by launching an activity without having to click on the "show monitor" button everytime. Using a separate activity for the monitor window would help me achieve just that.

**Comment by libxzr** [comment]
https://github.com/xzr467706992/PerfMon-Plus/releases/tag/v1.6
